name: option_set_example

environment:
  sdk: '>=2.12.0 < 3.0.0'

dependencies:
  option_set: ^0.0.2

dev_dependencies:
  build_runner: ^2.3.2
  build_verify: ^3.0.0

dependency_overrides:
  option_set:
    path: ../