name: option_set_example

environment:
  sdk: '>=2.1.0 < 3.0.0'

dependencies:
  option_set: ^0.0.1

dev_dependencies:
  build_runner: ^1.0.0
  build_verify: ^1.1.0

dependency_overrides:
  option_set:
    path: ../