builders:
  option_set_gen:
    import: "package:option_set/builder.dart"
    builder_factories: ["optionSetBuilder"]
    build_extensions: {".dart": ["option_set.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]