builders:
  option_set:
    import: "package:option_set/src/generator/builder.dart"
    builder_factories: ["optionSetBuilder"]
    build_extensions: {".dart": ["option_set.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]