name: option_set
description: A Dart package for working with option sets (i.e. bitmasks).
version: 0.0.1
author: Juan Diego Fajardo <jfajardo200@gmail.com>
homepage: https://github.com/kuanfajardo/dart-optionset

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  # Generator
  analyzer: ^0.36.3
  build: ^1.1.4
  source_gen: ^0.9.4
  code_builder: ^3.2.0
  dart_style: ^1.2.9

dev_dependencies:
  test: ^1.6.5

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
