name: option_set
description: A Dart package for working with option sets (i.e. bitmasks).
version: 0.0.2
author: Juan Diego Fajardo <jfajardo200@gmail.com>
homepage: https://github.com/kuanfajardo/dart-optionset

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  # Generator
  analyzer: ^5.2.0
  build: ^2.3.1
  source_gen: ^1.2.6
  code_builder: ^4.3.0
  dart_style: ^2.2.4

dev_dependencies:
  test: ^1.6.5

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
