name: option_set
description: A Dart package for working with option sets (i.e. bitmasks).
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:

dev_dependencies:
  test: ^1.6.5

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
